version: 1.2
workflows:
 - name: freyja_other_pathogens
   subclass: WDL
   primaryDescriptorPath: /wdls/main_freyja_other_pathogens.wdl
 - name: universal_primers_flu_alignment
   subclass: WDL
   primaryDescriptorPath: /wdls/main_universal_primers_flu_alignment.wdl